// Bundle the same modules for the Code Editor, GEE libraries and Python runner.
const fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.resolve(__dirname,'..'),prefix='users/calvites1990/CH-GEE_Improved:';
const source=n=>fs.readFileSync(path.join(root,n+'.js'),'utf8').replace(/^\uFEFF/,'');
const local=s=>s.replace(/require\(('users\/calvites1990\/CH-GEE_Improved:[^']+')\)/g,'localRequire($1)');
function bundle(entry,library=false){
 const needed=new Set();
 function collect(n){for(const m of source(n).matchAll(/require\('users\/calvites1990\/CH-GEE_Improved:([^']+)'\)/g)){if(!needed.has(m[1])){needed.add(m[1]);collect(m[1]);}}}
 collect(entry);let s='// Generated by tools/build.cjs; edit source modules.\n(function(hostRequire, entryExports){\nvar factories={},cache={};\n';
 for(const n of needed)s+='factories['+JSON.stringify(prefix+n)+']=function(exports){\n'+local(source(n))+'\n};\n';
 s+='function localRequire(n){if(!factories[n])return hostRequire(n);if(!cache[n]){cache[n]={};factories[n](cache[n]);}return cache[n];}\n(function(exports){\n'+local(source(entry))+'\n})(entryExports);\n})(require,'+(library?'exports':'{}')+');\n';
 new vm.Script(s,{filename:entry});return s;
}
for(const f of fs.readdirSync(root).filter(f=>f.endsWith('.js'))){new vm.Script(source(f.slice(0,-3)),{filename:f});fs.copyFileSync(path.join(root,f),path.join(root,'code_editor',f));}
for(const entry of ['CH-GEE','Run_Local','Run_And_Export'])fs.writeFileSync(path.join(root,'dist',entry+'.js'),bundle(entry));
fs.writeFileSync(path.join(root,'dist','CH-GEE_main.js'),bundle('CH-GEE_main',true));
console.log('Built single-map app, main library and two function examples.');
